### ISSUE TITLE
Flickr-Fire Dataset incomplete?

### ISSUE THREAD

**Issue by angel-ayala** [mtcazzolato/dsw2017#1]
Hi, I'm using your dataset for a research work and the Flickr-Fire folder only contains 956 images and in your paper talks about 2000 images, 1000 with fire and 1000 without it.

Is there correct the 956 images or is something else?

**Comment by angel-ayala** [comment]
Was my error, the folder contains the 1000 images, but I realize that in the flamesId.txt file, 16 images name are repeated. Those are:


83962387.jpg
367586911.jpg
3159781659.jpg
3403768393.jpg
3603000778.jpg
3673694492.jpg
4875032633.jpg
4992345011.jpg
5445919410.jpg
5838654139.jpg
5839233116.jpg
6004849611.jpg
7170061857.jpg
9710618486.jpg
9719800603.jpg
14081161928.jpg

The number which I was previously talking isn't 956 but 984 images, which plus the 16 repeated make 1000.

Regards

**Comment by mtcazzolato** [comment]
Hello, Angel.

We reported that Flickr-Fire has 2,000 images: 1,000 of label 'flame', and 1,000 of label 'not flame'.

Notice that FiSmo has three directories with the image files:

-> FiSmo/FiSmo-Images/Flickr-FireSmoke/imgs/
-> FiSmo/FiSmo-Images/Flickr-Fire/Flickr-Fire_flame/
-> FiSmo/FiSmo-Images/BoWFire/dataset/img/

All listed images should be in at least one of such directories.

Thanks for reporting the repetitions on file "FiSmo/FiSmo-Images/Flickr-Fire/flamesId.txt".
I'll update the README file with this information.

Best regards.
